baseURL = "https://concord.sh/"
languageCode = "en-us"
title = "./concord.sh"
theme = "concord"
paginate = 10

[params]
  AuthorName = "0xC0ncord"
  GithubUser = "0xC0ncord"
  MatrixUser = "@concord:fuwafuwatime.moe"
  AuthorEmail = "me _at_ concord dot sh"
  BTCAddressImgPath = "/img/wallet-btc.png"
  XMRAddressImgPath = "/img/wallet-xmr.png"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:year/:month/:title/"
